### ISSUE TITLE
Add support for MacroToolkit addon

### ISSUE THREAD

**Issue by F-I-R-E-F-O-X** [phanx-wow/MacroTooltip#1]
https://mods.curse.com/addons/wow/macro-toolkit

**Comment by Phanx** [comment]
Yes, that is the URL of the page where you can download release versions of this addon. Where/what is your actual request?

**Comment by F-I-R-E-F-O-X** [comment]
Lmao, sorry I meant to link http://www.curse.com/addons/wow/macro-toolkit
